Upload binaries napi to release.
apache/pulsar-client-node pull request #245
Opened 2022-11-10 08:45 UTC by shibd

### Motivation

At the end of the release CI, upload the binaries to `GitHub Release`. Make it easy for users to view and download these pre-built binaries.

PS: This has nothing to do with Apache's release process

### Modifications
- Add upload-release-action on release ci end.

### Documentation

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)

- [x] `doc-not-needed` 
(Please explain why)

- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

2022-11-10 08:49 UTC, BewareMyPower reviewed
Could you show an example workflow (maybe in your fork) to show the uploaded binaries?

2022-11-10 13:23 UTC, BewareMyPower reviewed
Do we need to upload the artifacts to the release page?

2022-11-10 14:57 UTC, shibd commented
> Do we need to upload the artifacts to the release page?

Yes, They are the same.

<img width="638" alt="image" src="https://user-images.githubusercontent.com/33416836/201125461-0c1c44da-c229-4189-bed7-9c0fbe9c352f.png">

2022-11-14 03:28 UTC, BewareMyPower requested changes
Sorry I didn't express clearly. You try to upload these artifacts to the release page, but is there any document to explain how to use it? For example, I downloaded napi-linux-musl-x64.tar.gz and uncompress it to have a `binding/Pulsar.node` file:

```
binding/Pulsar.node: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, with debug_info, not stripped
```

But I don't know how to use it because it's only a dynamic library. (BTW it looks the build is a debug build, maybe we should change it to a release build)

2022-11-14 03:31 UTC, BewareMyPower commented
Another concern is from comments [here](https://github.com/apache/pulsar-client-cpp/pull/72#issuecomment-1293494580), @merlimat what's your opinion about this PR that uploads some artifacts into the release page?

2022-11-14 04:18 UTC, shibd commented
> You try to upload these artifacts to the release page, but is there any document to explain how to use it?

Oh, I want to clarify that this has no impact on the average user. They are used through the `npm install pulsar-client`.

But for users who don't want to use the npm management package. They can be downloaded binaries through the `release page`.

Then use it like below(BTW: This approach does not require additional instructions in the documentation): 
```node
const Pulsar = require('Pulsar.node');

(async () => {
  // Create a client
  const clientConfig = {
    serviceUrl: 'pulsar://localhost:6650',
  };

  const client = new Pulsar.Client(clientConfig);
  await client.close();
})();


```

2022-11-14 04:44 UTC, BewareMyPower commented
> But for users who don't want to use the npm management package. 

Why not use the the NPM package since the artifacts uploaded to the release page are the same with the artifacts uploaded into NPM? If the artifacts are from a candidate version, it's better not to upload the artifacts to GitHub release page.

2022-11-14 04:46 UTC, BewareMyPower commented
> Then use it like below(BTW: This approach does not require additional instructions in the documentation):
> 
> ```js
> const Pulsar = require('./Pulsar.node');
> ```

It doesn't make sense to me. The examples under the https://github.com/apache/pulsar-client-node/tree/master/examples directory all uses:

```node
const Pulsar = require('pulsar-client');
```

It a user switched to a temporary release from an official release, they have to modify the existing code.

2022-11-14 06:13 UTC, shibd commented
> > But for users who don't want to use the npm management package.
> 
> Why not use the the NPM package since the artifacts uploaded to the release page are the same with the artifacts uploaded into NPM? If the artifacts are from a candidate version, it's better not to upload the artifacts to GitHub release page.

Make sense. I closed this PR.

2022-11-14 06:13 UTC, closed without merging