feat: Expose resume and pause listeners
apache/pulsar-client-node pull request #246
Opened 2022-11-16 06:39 UTC by jaysonsantos

This should give developers the ability to limit the inflight messages with some sort of semaphore/tokenbucket

Fixes #<xyz>

Master Issue: #<xyz>

### Motivation

### Modifications

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)

- [ ] `doc-not-needed` 
(Please explain why)

- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

2022-11-21 15:25 UTC, shibd requested changes

2022-11-21 15:25 UTC, shibd commented on tests/end_to_end.test.js
> +          messageConsumer.pauseMessageListener();
Please add unit tests for both interface usage scenarios.

2023-01-27 06:55 UTC, massakam commented
@jaysonsantos 
Could you add a test case as @shibd commented? In addition, please resolve the conflict.

2023-04-11 10:51 UTC, RobertIndie requested changes
I think this is an issue related to https://github.com/apache/pulsar-client-node/issues/308. It's been fixed by https://github.com/apache/pulsar-client-node/pull/309.

Note that we don't have `pauseMessageListener` and `resumeMessageListener` methdo for the Java client API. If we want to add new APIs that don't exist in the Java client. We need to raise a PIP to discuss it. Anyway, I don't think we need these two APIs.

2024-04-03 07:58 UTC, closed without merging